# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{crondonkulous}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Bock"]
  s.date = %q{2009-08-24}
  s.description = %q{A generator and conventions for using cron with rake tasks in a rails application.}
  s.email = %q{dbock@codesherpas.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "History.txt",
     "Manifest.txt",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "crondonkulous.gemspec",
     "lib/crondonkulous.rb",
     "lib/crondonkulous/recipes.rb",
     "rails_generators/crondonkulous_generator.rb",
     "rails_generators/templates/crondonkulous.rake",
     "rails_generators/templates/crontab.erb",
     "rails_generators/templates/readme.txt",
     "script/console",
     "script/destroy",
     "script/generate",
     "test/test_crondonkulous.rb",
     "test/test_helper.rb"
  ]
  s.has_rdoc = true
  s.homepage = %q{http://github.com/bokmann/crondonkulous}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.1}
  s.summary = %q{A generator and conventions for using cron with rake tasks in a rails application.}
  s.test_files = [
    "test/test_crondonkulous.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 2

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<lockfile>, [">= 1.4.0"])
    else
      s.add_dependency(%q<lockfile>, [">= 1.4.0"])
    end
  else
    s.add_dependency(%q<lockfile>, [">= 1.4.0"])
  end
end
